name: Pylint
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Pylint
        run: pip install pylint
      - name: Run Check
        run: pylint --disable=all core_logic.py q_shield.py w_vault.py
